# Generated by Django 4.2.7 on 2023-11-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samsecapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='firstname',
            new_name='firstName',
        ),
    ]
